### ISSUE TITLE
默认的Android配置，运行手机端无任何反应

### ISSUE THREAD

**Issue by liwanyin** [macacajs/NoSmoke#25]
用项目下面的默认设置，使用Android的配置，手机端无反应，请帮忙看下Log，谢谢了！

 macaca server --verbose                                                                                                
> index.js:18:12 [master] pid:5688 webdriver server start with config:                                                  
{ port: 3456,                                                                                                           
 verbose: true,                                                                                                         
 always: true,                                                                                                          
 ip: '10.1.46.86',                                                                                                      
 host: 'MD01-PC',                                                                                                       
 loaded_time: '2017-09-15 15:15:36' }                                                                                   
> middlewares.js:17:10 [master] pid:5688 base middlewares attached                                                      
> router.js:127:10 [master] pid:5688 router set                                                                         
> webdriver sdk launched                                                                                                
> responseHandler.js:11:12 [master] pid:5688 Recieve HTTP Request from Client[2017-09-15 15:15:49]: method: POST url: /w
/hub/session, jsonBody: {"desiredCapabilities":{"isWaitActivity":true,"activity":"LoginActivity","app":"https://npmcdn.c
m/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk"}}               
> session.js:47:10 [master] pid:5688 Creating session, sessionId: b6b3d929-36ec-40ef-8cd5-5f4ea5f7ef09.                 
> please run: `npm install macaca-undefined -g`                                                                         
> session.js:40:14 [master] pid:5688 Error: Cannot find module 'macaca-undefined'                                       
   at Function.Module._resolveFilename (module.js:469:15)                                                               
   at Function.Module._load (module.js:417:25)                                                                          
   at Module.require (module.js:497:17)                                                                                 
   at require (internal/module.js:20:19)                                                                                
   at detectDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\c
ntrollers\session.js:36:20)                                                                                             
   at Object.createDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\s
rver\controllers\session.js:10:18)                                                                                      
   at next (native)                                                                                                     
   at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:65:19)            
   at C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:54:5                           
   at Object.co (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:50:10)              
> responseHandler.js:56:12 [master] pid:5688 Send Error Respone to Client: Error: >> session.js:40:14 [master] pid:5688 
rror: Cannot find module 'macaca-undefined'                                                                             
   at Function.Module._resolveFilename (module.js:469:15)                                                               
   at Function.Module._load (module.js:417:25)                                                                          
   at Module.require (module.js:497:17)                                                                                 
   at require (internal/module.js:20:19)                                                                                
   at detectDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\c
ntrollers\session.js:36:20)                                                                                             
   at Object.createDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\s
rver\controllers\session.js:10:18)                                                                                      
   at next (native)                                                                                                     
   at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:65:19)            
   at C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:54:5                           
   at Object.co (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:50:10)              
> responseHandler.js:62:14 [master] pid:5688 Error: >> session.js:40:14 [master] pid:5688 Error: Cannot find module 'mac
ca-undefined'                                                                                                           
   at Function.Module._resolveFilename (module.js:469:15)                                                               
   at Function.Module._load (module.js:417:25)                                                                          
   at Module.require (module.js:497:17)                                                                                 
   at require (internal/module.js:20:19)                                                                                
   at detectDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\c
ntrollers\session.js:36:20)                                                                                             
   at Object.createDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\s
rver\controllers\session.js:10:18)                                                                                      
   at next (native)                                                                                                     
   at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:65:19)            
   at C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:54:5                           
   at Object.co (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:50:10)              
   at Logger.error (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\xlogger\lib\xlogger.js:169:9)
                                                                                                                        
   at detectDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\c
ntrollers\session.js:40:14)                                                                                             
   at Object.createDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\s
rver\controllers\session.js:10:18)                                                                                      
   at next (native)                                                                                                     
   at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:65:19)            
   at C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:54:5                           
   at Object.co (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:50:10)              
   at Object.toPromise (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:118:63)      
   at next (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:99:29)                   
   at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:69:7)             
                                                                                                                        
 Error: >> session.js:40:14 [master] pid:5688 Error: Cannot find module 'macaca-undefined'                              
     at Function.Module._resolveFilename (module.js:469:15)                                                             
     at Function.Module._load (module.js:417:25)                                                                        
     at Module.require (module.js:497:17)                                                                               
     at require (internal/module.js:20:19)                                                                              
     at detectDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server
controllers\session.js:36:20)                                                                                           
     at Object.createDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib
server\controllers\session.js:10:18)                                                                                    
     at next (native)                                                                                                   
     at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:65:19)          
     at C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:54:5                         
     at Object.co (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:50:10)            
     at Logger.error (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\xlogger\lib\xlogger.js:169:
)                                                                                                                       
     at detectDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server
controllers\session.js:40:14)                                                                                           
     at Object.createDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib
server\controllers\session.js:10:18)                                                                                    
     at next (native)                                                                                                   
     at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:65:19)          
     at C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:54:5                         
     at Object.co (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:50:10)            
     at Object.toPromise (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:118:63)    
     at next (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:99:29)                 
     at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:69:7)           
                                                                                                                        
> responseHandler.js:11:12 [master] pid:5688 Recieve HTTP Request from Client[2017-09-15 15:24:40]: method: POST url: /w
/hub/session, jsonBody: {"desiredCapabilities":{"isWaitActivity":true,"activity":"LoginActivity","app":"https://npmcdn.c
m/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk"}}               
> session.js:47:10 [master] pid:5688 Creating session, sessionId: 956b3a22-833a-4d86-acb5-359397079129.                 
> please run: `npm install macaca-undefined -g`                                                                         
> session.js:40:14 [master] pid:5688 Error: Cannot find module 'macaca-undefined'                                       
   at Function.Module._resolveFilename (module.js:469:15)                                                               
   at Function.Module._load (module.js:417:25)                                                                          
   at Module.require (module.js:497:17)                                                                                 
   at require (internal/module.js:20:19)                                                                                
   at detectDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\c
ntrollers\session.js:36:20)                                                                                             
   at Object.createDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\s
rver\controllers\session.js:10:18)                                                                                      
   at next (native)                                                                                                     
   at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:65:19)            
   at C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:54:5                           
   at Object.co (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:50:10)              
> responseHandler.js:56:12 [master] pid:5688 Send Error Respone to Client: Error: >> session.js:40:14 [master] pid:5688 
rror: Cannot find module 'macaca-undefined'                                                                             
   at Function.Module._resolveFilename (module.js:469:15)                                                               
   at Function.Module._load (module.js:417:25)                                                                          
   at Module.require (module.js:497:17)                                                                                 
   at require (internal/module.js:20:19)                                                                                
   at detectDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\c
ntrollers\session.js:36:20)                                                                                             
   at Object.createDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\s
rver\controllers\session.js:10:18)                                                                                      
   at next (native)                                                                                                     
   at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:65:19)            
   at C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:54:5                           
   at Object.co (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:50:10)              
> responseHandler.js:62:14 [master] pid:5688 Error: >> session.js:40:14 [master] pid:5688 Error: Cannot find module 'mac
ca-undefined'                                                                                                           
   at Function.Module._resolveFilename (module.js:469:15)                                                               
   at Function.Module._load (module.js:417:25)                                                                          
   at Module.require (module.js:497:17)                                                                                 
   at require (internal/module.js:20:19)                                                                                
   at detectDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\c
ntrollers\session.js:36:20)                                                                                             
   at Object.createDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\s
rver\controllers\session.js:10:18)                                                                                      
   at next (native)                                                                                                     
   at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:65:19)            
   at C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:54:5                           
   at Object.co (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:50:10)              
   at Logger.error (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\xlogger\lib\xlogger.js:169:9)
                                                                                                                        
   at detectDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\c
ntrollers\session.js:40:14)                                                                                             
   at Object.createDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\s
rver\controllers\session.js:10:18)                                                                                      
   at next (native)                                                                                                     
   at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:65:19)            
   at C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:54:5                           
   at Object.co (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:50:10)              
   at Object.toPromise (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:118:63)      
   at next (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:99:29)                   
   at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:69:7)             
                                                                                                                        
 Error: >> session.js:40:14 [master] pid:5688 Error: Cannot find module 'macaca-undefined'                              
     at Function.Module._resolveFilename (module.js:469:15)                                                             
     at Function.Module._load (module.js:417:25)                                                                        
     at Module.require (module.js:497:17)                                                                               
     at require (internal/module.js:20:19)                                                                              
     at detectDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server
controllers\session.js:36:20)                                                                                           
     at Object.createDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib
server\controllers\session.js:10:18)                                                                                    
     at next (native)                                                                                                   
     at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:65:19)          
     at C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:54:5                         
     at Object.co (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:50:10)            
     at Logger.error (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\xlogger\lib\xlogger.js:169:
)                                                                                                                       
     at detectDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server
controllers\session.js:40:14)                                                                                           
     at Object.createDevice (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib
server\controllers\session.js:10:18)                                                                                    
     at next (native)                                                                                                   
     at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:65:19)          
     at C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:54:5                         
     at Object.co (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:50:10)            
     at Object.toPromise (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:118:63)    
     at next (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:99:29)                 
     at onFulfilled (C:\Users\MD01\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:69:7)

**Comment by SamuelZhaoY** [comment]
看上去， 是你的yml 配置有问题哈， platform有声明android 吗？

**Comment by liwanyin** [comment]
配置如下，请看看：

**Comment by liwanyin** [comment]
# 1. Initialization option
desiredCapabilities:
 isWaitActivity: true
 activity: 'LoginActivity'
 app: 'https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk'

# 2. Crawling option
crawlingConfig:
  platform: 'Android'
  targetElements:
    loginAccount:
      actionType  : 2
      searchValue : 'please input username'
      actionValue : '中文+Test+12345678'
    loginPassword:
      actionType  : 2
      searchValue : 'please input password'
      actionValue : '111111'
    loginButton:
      actionType  : 1
      searchValue : 'Login'
    alertConfirm:
      actionType  : 1
      searchValue : 'yes'
  clickTypes:
   - 'android.widget.ImageView'
   - 'android.widget.TextView'
   - 'android.widget.Button'
  editTypes:
   - 'android.widget.EditText'
  tabBarTypes:
   - 'android.widget.TabWidget'

**Comment by SamuelZhaoY** [comment]
# 1. Initialization option
desiredCapabilities:
 isWaitActivity: true
 activity: 'LoginActivity'
 app: 'https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk'

少了 platformName: android

#  platformName: 'android'
#  isWaitActivity: true
#  activity: 'LoginActivity'
#  app: 'https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk'

**Comment by liwanyin** [comment]
多谢你的耐心指教，我好好学习下，在我们的项目上用起来！
