### ISSUE TITLE
win10 web默认配置 也报错。

### ISSUE THREAD

**Issue by Archer456** [macacajs/NoSmoke#29]
`>> use default chromedriver version!
>> chromedriver bin path: D:\nodejs\node-global\node_modules\macaca-chrome\node_modules\macaca-chromedriver\exec\chromedriver2.20.exe
>> Starting ChromeDriver 2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067) on port 9515
Only local connections are allowed.

>> chromedriver starting success.
>> proxy.js:51:14 [master] pid:9584 Proxy: /status:GET to http://localhost:9515/wd/hub/status:GET with body:
>> proxy.js:59:16 [master] pid:9584 Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"10.0\"}}}"
>> proxy.js:51:14 [master] pid:9584 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"platformName":"Desktop","browserName":"Chrome","url":"https://macacajs.github.io"}}
[18824:9580:1023/153914.374:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.

DevTools listening on ws://127.0.0.1:12751/devtools/browser/d3b3b544-9d53-489e-b41a-bdfbdd0c0824
[18824:5524:1023/153914.553:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.587:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.597:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.605:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.615:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.628:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.637:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.644:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.654:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.661:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.673:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.682:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.694:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.707:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.714:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.724:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.738:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.746:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.761:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.782:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.796:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.808:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.824:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.839:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
[18824:5524:1023/153914.849:ERROR:persistent_memory_allocator.cc(815)] Corruption detected in shared-memory segment.
Error: chromedriver proxy error with: Error: read ECONNRESET
    at Request.e [as _callback] (D:\nodejs\node-global\node_modules\macaca-chrome\node_modules\macaca-chromedriver\lib\proxy.js:57:25)
    at self.callback (D:\nodejs\node-global\node_modules\macaca-chrome\node_modules\request\request.js:199:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\nodejs\node-global\node_modules\macaca-chrome\node_modules\request\request.js:821:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
>> macaca-chromedriver.js:168:18 [master] pid:9584 chromedriver exit with code: 3221225477, signal: null
>> proxy.js:51:14 [master] pid:9584 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"platformName":"Desktop","browserName":"Chrome","url":"https://macacajs.github.io"}}
Error: chromedriver proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9515
    at Request.e [as _callback] (D:\nodejs\node-global\node_modules\macaca-chrome\node_modules\macaca-chromedriver\lib\proxy.js:57:25)
    at self.callback (D:\nodejs\node-global\node_modules\macaca-chrome\node_modules\request\request.js:199:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\nodejs\node-global\node_modules\macaca-chrome\node_modules\request\request.js:821:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
>> proxy.js:51:14 [master] pid:9584 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"platformName":"Desktop","browserName":"Chrome","url":"https://macacajs.github.io"}}`

然后会循环一直报该段错误 一直循环报：
`Error: chromedriver proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9515
    at Request.e [as _callback] (D:\nodejs\node-global\node_modules\macaca-chrome\node_modules\macaca-chromedriver\lib\proxy.js:57:25)
    at self.callback (D:\nodejs\node-global\node_modules\macaca-chrome\node_modules\request\request.js:199:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\nodejs\node-global\node_modules\macaca-chrome\node_modules\request\request.js:821:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
>> proxy.js:51:14 [master] pid:9584 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"platformName":"Desktop","browserName":"Chrome","url":"https://macacajs.github.io"}}`

配置如下：

---
desiredCapabilities:
  platformName: 'Desktop'
  browserName: 'Chrome'
  url: 'https://macacajs.github.io'
crawlingConfig:
  clickTypes:
    - 'a'
  editTypes:
    - 'input'
...

C:\Users\cmd>macaca doctor

  macaca-doctor version: 2.0.3

  Node.js checklist:

  node env: D:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_121`
  ANDROID_HOME is set to `D:\Android\android-sdk-windows`
  Platforms is set to `D:\Android\android-sdk-windows\platforms\android-26`
  ADB tool is set to `D:\Android\android-sdk-windows\platform-tools\adb.exe`
  GRADLE_HOME is set to `D:\gradle-3.5`

  Installed driver list:

  android: 2.0.40
  chrome: 1.0.7
  electron: 1.1.11

**Comment by SamuelZhaoY** [comment]
chromedriver 目前存在问题.  需要macaca 驱动层解决

**Comment by SamuelZhaoY** [comment]
@xudafeng

**Comment by xudafeng** [comment]
@SamuelZhaoY 使用2.33
