### ISSUE TITLE
 get apk mainifest failed

### ISSUE THREAD

**Issue by wangxiaote** [macacajs/NoSmoke#48]
环境：win10 ；android studio 3.0; java1.8; android sdk 27;
>> uiautomator-client.js:74:14 [master] pid:15996 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9009<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0
>> UIAutomatorWD http server ready
>> responseHandler.js:56:12 [master] pid:15996 Send Error Respone to Client: get apk mainifest failed with: TypeError: "file" argument must be a non-empty string

  InternalServerError: Internal Server Error
      at Object.throw (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\koa\lib\context.js:91:23)
      at Object.module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\responseHandler.js:59:17)
      at module.exports.throw (<anonymous>)
      at onRejected (C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:81:24)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by xiaoluohardup** [comment]
请问这个问题你解决了吗？

**Comment by SamuelZhaoY** [comment]
@wangxiaote apk 路径配置出错.  请参考demo 进行配置.

**Comment by xiaoluohardup** [comment]
@SamuelZhaoY 我这边的apk的路径是这样的 ，请问哪里错了呢？

            File directory = new File(".");
            String appPath = directory.getCanonicalPath() + "\\src\\app\\";
            String platform = "android";
            JSONObject porps = new JSONObject();
            porps.put("platformName", platform);
            porps.put("app", appPath + "zhijia-debug.apk");
