### ISSUE TITLE
 ios-deploy[1940:43249] [ !! ] Timed out waiting for device.

### ISSUE THREAD

**Issue by if1else0** [macacajs/NoSmoke#57]
Hi 安装文件只能是.app的还是也可以支持.ipa ,然后安装的时候出现如下错误是什么原因，谢谢

>> port: 3456 was occupied, changed port: 3465
>> index.js:18:12 [master] pid:1936 webdriver server start with config:
 { port: 3465,
  verbose: true,
  always: true,
  ip: '192.168.9.7',
  host: 'Aarons-MacBook-Pro.local',
  loaded_time: '2018-05-23 23:57:29' }
>> middlewares.js:17:10 [master] pid:1936 base middlewares attached
>> router.js:133:10 [master] pid:1936 router set
>> Macaca server started
>> responseHandler.js:11:12 [master] pid:1071 Recieve HTTP Request from Client[2018-05-23 23:57:35]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"iOS","deviceName":"iPhone 6","autoAcceptAlerts":true,"xcodeOrgId":"S6NQ524Y5V","xcodeSigningId":"iPhone Developer","bundleId":"com.maa.netTestDemo","app":"/Users/aaronyang/Downloads/netLibraryTextDemo.app","udid":"dfeb73710c93352847220dd9c8ff3bee8b176a13"}}
>> session.js:58:10 [master] pid:1071 Creating session, sessionId: 824de475-03eb-4072-a009-fde9a4a65f01.
>> helper.js:176:12 [master] pid:1071 Using local app form /Users/aaronyang/Downloads/netLibraryTextDemo.app
>> responseHandler.js:56:12 [master] pid:1071 Send Error Respone to Client: Error: 2018-05-23 23:57:40.746 ios-deploy[1940:43249] [ !! ] Timed out waiting for device.

>> responseHandler.js:62:14 [master] pid:1071 Error: 2018-05-23 23:57:40.746 ios-deploy[1940:43249] [ !! ] Timed out waiting for device.

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/_ios-device@1.0.0@ios-device/lib/helper.js:46:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

  Error: 2018-05-23 23:57:40.746 ios-deploy[1940:43249] [ !! ] Timed out waiting for device.

      at ChildProcess.<anonymous> (/usr/local/lib/node_modules/macaca-ios/node_modules/_ios-device@1.0.0@ios-device/lib/helper.js:46:17)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Socket.stream.socket.on (internal/child_process.js:346:11)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at Pipe._handle.close [as _onclose] (net.js:554:12)

**Comment by SamuelZhaoY** [comment]
目前只支持 .app 文件

**Comment by SamuelZhaoY** [comment]
从log 上看是一直找不到设备,  使用的模拟器？ 真机？
