### ISSUE TITLE
Error with macaca-reporter when running nosmoke

### ISSUE THREAD

**Issue by santius** [macacajs/NoSmoke#66]
Hello,

I am facing the following using when trying to run nosmoke on mac:

When I try to run the following command:

```
# initialize macaca server
macaca server --verbose &

# initialize nosmoke
nosmoke
```

I get this error:

```
Error: Cannot find module 'macaca-reporter/test/mock'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/USERNAME/.nvm/versions/node/v8.14.0/lib/node_modules/nosmoke/lib/server/router.js:14:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

I am running on:

- Node v8.14
- OSX Mojave

**Comment by SamuelZhaoY** [comment]
update "macaca-reporter": "^1.0.18", to "macaca-reporter": "^1.1.11", and re-run it

**Comment by xudafeng** [comment]
@SamuelZhaoY 你这里依赖需要升级一下？

https://github.com/macacajs/NoSmoke/blob/master/package.json#L25

**Comment by trimQiu** [comment]
I hava this question too.
And I changed macaca-report version to "^1.1.11", it still didn't work. Nosmoke gave me the same error.

**Comment by SamuelZhaoY** [comment]
@trimQiu will check this out asap

**Comment by 123tanliheng** [comment]
I have the same problem in windows.

**Comment by SamuelZhaoY** [comment]
@trimQiu @santius  npm i macaca-reporter@1.1.12 --save , will solve,  or update to nosmoke@1.1.10

**Comment by santius** [comment]
It worked for me,

Thanks
