### ISSUE TITLE
common/logger.js platform不为ios或android时，cmd会为空字符串，导致报错

### ISSUE THREAD

**Issue by zxsky316** [macacajs/NoSmoke#83]
想用nosmoke做web-pc的遍历测试，发现会报错，最后定位到了common/logger.js中，
报错信息如下
TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:384:11)
    at exports.spawn (child_process.js:497:38)
    at Object.exports.execFile (child_process.js:213:15)
    at exports.exec (child_process.js:143:18)
    at Logger.filterDeviceLogs (/Users/zhengxu/Documents/software/npm/lib/node_modules/nosmoke/lib/common/logger.js:62:16)
    at EventEmitter.root.eventEmmiter.addListener (/Users/zhengxu/Documents/software/npm/lib/node_modules/nosmoke/lib/crawler/index.js:56:10)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at WDClient.onSessionCreated (/Users/zhengxu/Documents/software/npm/lib/node_modules/nosmoke/lib/wd-client.js:54:21)
    at that.send (/Users/zhengxu/Documents/software/npm/lib/node_modules/nosmoke/lib/wd-client.js:45:14)
-----> Crawling Finished: <----- 
 TypeError: "file" argument must be a non-empty string

注释掉index.js中的  logger.filterDeviceLogs(root.config);
可以正常运行nosmoke命令，配置文件中时对所有的 a标签进行点击操作，但是实际运行能打开页面，但是未发生点击操作，能帮忙个看下是什么问题吗？

**Comment by SamuelZhaoY** [comment]
logger 的问题不影响pc-web 下的爬行实现， 应该是别的问题.  此处exception会修复
