### ISSUE TITLE
Error: The module '/usr/local/lib/node_modules/nosmoke/node_modules/canvas/build/Release/canvas.node' was compiled against a different Node.js version using

### ISSUE THREAD

**Issue by chensheng0619** [macacajs/NoSmoke#92]
`udid: 66J5T19117004171
config loaded: 
 {"testingPeriod":1800,"testingDepth":8,"takeScreenShot":true,"newCommandTimeout":2,"launchTimeout":3,"packages":".*","maxActionPerPage":15,"asserts":[],"targetElements":{},"exclusivePattern":"","platform":"android","clickTypes":[],"editTypes":[],"horizontalScrollTypes":[],"verticalScrollTypes":[],"tabBarTypes":[],"exclusiveTypes":[],"blacklist":[],"strategy":"ocr","depth":100,"duration":1800,"triggers":["Login","Allow","OK","Cancel"],"exclude":[],"deviceType":"","configFile":"/Users/mac/Documents/workspace/github/NoSmoke/demo/crawler.config-android.yml"} 

Error: The module '/usr/local/lib/node_modules/nosmoke/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:815:18)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/nosmoke/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
(node:59948) [DEP0016] DeprecationWarning: 'root' is deprecated, use 'global'

`

**Comment by liuwei12931902** [comment]
这个报错解决了吗

**Comment by liuwei12931902** [comment]
试试node 8 版本

**Comment by upsnailNostalgia** [comment]
cd /usr/local/lib/node_modules/nosmoke,然后rm -rvf node_modules，再npm install，最后重启就能在浏览器上看到猴子了
